# Generated by Django 6.0.2 on 2026-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='MobileNo',
            field=models.BigIntegerField(null=True),
        ),
    ]
